<header class="row">
    <div class="container">
        <div class="col-md-4"><img src="img/logo-libratel.png" /></div>
        <div class="col-md-4">PESQUISA</div>
        <div class="col-md-4">
            <a href="" class="btn btn-block btn-orcamento">SOLICITAR ORÇAMENTO</a>
        </div>
    </div>
</header>

<nav class="row" id="menu">
    <div class="container">
        <ul>
            <li><a href="/preview/public/">Home</a></li>
            <li><a href="">Quem Somos</a></li>
            <li><a href="">Serviços</a></li>
            <li class="active"><a href="/preview/public/produto">Produtos</a></li>
            <li><a href="">Clientes</a></li>
            <li><a href="">Contato</a></li>
        </ul>
    </div>
</nav>

<div class="row">
    <div class="container" id="destaques">
        <h2>DESTAQUES</h2>

        <div class="col-md-4 destaque">
            <div class="thumbnail">
                <img src="img/motor-portao.jpg" alt="...">

                <div class="caption">
                    <h3>Motor para Portão eletronico</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 destaque">
            <div class="thumbnail">
                <img src="img/interfone.jpg" alt="...">

                <div class="caption">
                    <h3>Interfone Digital</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 destaque">
            <div class="thumbnail">
                <img src="img/portao-basculante.jpg" alt="...">

                <div class="caption">
                    <h3>Portão Basculante</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="container" id="outros_produtos">
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera1.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera2.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera1.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera2.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera1.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera2.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera1.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera2.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera1.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera2.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

