<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Libratel Segurança'); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//                        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/libratel-theme.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100' rel='stylesheet' type='text/css'>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<!--        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
<!--            <div class="container">-->
<!--                <div class="navbar-header">-->
<!--                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--                        <span class="icon-bar"></span>-->
<!--                        <span class="icon-bar"></span>-->
<!--                        <span class="icon-bar"></span>-->
<!--                    </button>-->
<!--                    <a class="navbar-brand" href="--><?php //echo $this->url('home') ?><!--"><img src="-->
<?php //echo $this->basePath('img/zf2-logo.png') ?><!--" alt="Zend Framework 2"/>&nbsp;-->
<?php //echo $this->translate('Skeleton Application') ?><!--</a>-->
<!--                </div>-->
<!--                <div class="collapse navbar-collapse">-->
<!--                    <ul class="nav navbar-nav">-->
<!--                        <li class="active"><a href="--><?php //echo $this->url('home') ?><!--">-->
<?php //echo $this->translate('Home') ?><!--</a></li>-->
<!--                    </ul>-->
<!--                </div><!--/.nav-collapse -->
<!--            </div>-->
<!--        </nav>-->
<div>
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <div class="container">
            <h1>Libratel</h1>

            <div class="col-md-3">
                <p>Rua Santos Dumont, 839<br/>
                    Vila Operária, Maringá - PR<br/>
                    Cep: 87050-100</p>
            </div>

            <div class="col-md-3">
                <p>Plantão:<br/>
                    (44) 9973-6080<br/>
                    (44) 3226-8778</p>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <img src="img/logo-libratel.png" alt="...">
            </div>
            <div class="col-md-12">
                <hr/>
                <p style="text-align: right;">&copy; <?php echo date('Y') ?> Desenvolvido por Devmake Systems.</p>
            </div>
        </div>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
