<header class="row">
    <div class="container">
        <div class="col-md-4"><img src="img/logo-libratel.png"/></div>
        <div class="col-md-4">PESQUISA</div>
        <div class="col-md-4">
            <a href="" class="btn btn-block btn-orcamento">SOLICITAR ORÇAMENTO</a>
        </div>
    </div>
</header>

<nav class="row" id="menu">
    <div class="container">
        <ul>
            <li class="active"><a href="/preview/public/">Home</a></li>
            <li><a href="">Quem Somos</a></li>
            <li><a href="">Serviços</a></li>
            <li><a href="/preview/public/produto">Produtos</a></li>
            <li><a href="">Clientes</a></li>
            <li><a href="">Contato</a></li>
        </ul>
    </div>
</nav>

<div class="row" id="banner">
    <div class="container">
        <img src="img/banner.png"/>
    </div>
</div>

<div class="row">
    <div class="container" id="destaques">
        <h2>DESTAQUES</h2>

        <div class="col-md-4 destaque">
            <div class="thumbnail">
                <img src="img/motor-portao.jpg" alt="...">

                <div class="caption">
                    <h3>Motor para Portão eletronico</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 destaque">
            <div class="thumbnail">
                <img src="img/interfone.jpg" alt="...">

                <div class="caption">
                    <h3>Interfone Digital</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 destaque">
            <div class="thumbnail">
                <img src="img/portao-basculante.jpg" alt="...">

                <div class="caption">
                    <h3>Portão Basculante</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="container" id="outros_produtos">
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera1.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera2.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumbnail">
                <img src="img/camera3.jpg" alt="...">

                <div class="caption">
                    <h3>Produto 1</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                    <p><a href="#"
                          class="btn btn-block btn-addorcamento"
                          role="button">Adicionar ao Orçamento</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div id="enquete">
                <h3>Enquete</h3>

                <form>
                    <label>Qual seu sistema de segurança?</label>

                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                            Cameras de Segurança
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                            Portão Eletrônico
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios3" value="option2">
                            Cercas Elétricas
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios4" value="option2">
                            Interfonia Digital
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2">
                            Cães de Guarda
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios" id="optionsRadios6" value="option2">
                            Nenhum Sistema
                        </label>
                    </div>
                    <a href="#"
                       class="btn btn-warning"
                       role="button">Votar</a>
                </form>
            </div>
        </div>
    </div>
</div>

<br/>
<div class="row">
    <div class="container">
        <div class="col-md-12" id="depoimentos">
            <div class="col-md-2"><img src="img/fabio.jpg" alt="..." class="img-circle"></div>
            <div class="col-md-10">
                <h1>Os produtos da Libratel são muito bons. Eu recomendo!</h1>
                <span>Fabio Baía</span>
            </div>
        </div>
    </div>
</div>
<br/>
<div class="row">

    <div class="container">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Dicas de Segurança</h3>
                </div>
                <div class="panel-body">
                    <h4>Quando você estiver no carro:</h4>

                    <p>Não deixe as chaves no contato (ignição) de seu carro, ainda que seja por alguns momentos, nem
                        entregue-as à pessoas entranhas.</p>

                    <p>Obedeça as regras de trânsito.</p>

                    <p>Quando seu veículo apresentar defeito, chame um mecânico de sua confiança.</p>

                    <p><a class="btn btn-success pull-right" href="">Mais dicas &raquo;</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Dicas de Segurança</h3>
                </div>
                <div class="panel-body">
                    <h4>Quando você estiver no carro:</h4>

                    <p>Não deixe as chaves no contato (ignição) de seu carro, ainda que seja por alguns momentos, nem
                        entregue-as à pessoas entranhas.</p>

                    <p>Obedeça as regras de trânsito.</p>

                    <p>Quando seu veículo apresentar defeito, chame um mecânico de sua confiança.</p>

                    <p><a class="btn btn-success pull-right" href="">Mais dicas &raquo;</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Dicas de Segurança</h3>
                </div>
                <div class="panel-body">
                    <h4>Quando você estiver no carro:</h4>

                    <p>Não deixe as chaves no contato (ignição) de seu carro, ainda que seja por alguns momentos, nem
                        entregue-as à pessoas entranhas.</p>

                    <p>Obedeça as regras de trânsito.</p>

                    <p>Quando seu veículo apresentar defeito, chame um mecânico de sua confiança.</p>

                    <p><a class="btn btn-success pull-right" href="">Mais dicas &raquo;</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
